[package]
name = "rusty-bolt-stub"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
nom-supreme = "0.8.0"
anyhow = "1.0.86"
tokio = "1.39.3"
clap = { version = "4.5.16", features = ["derive"] }

[dev-dependencies]
rstest ="0.22.0"
