[package]
name = "rusty-bolt-stub"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
nom-span = { version = "0.1.1", path = "nom-span" }
nom-supreme = "0.8.0"
anyhow = "1.0.86"
tokio = { version = "1.40.0", features = ["full"] }
clap = { version = "4.5.16", features = ["derive"] }
chrono = "0.4.38"
itertools = "0.13.0"
chrono-tz = "0.9.0"
duplicate = "1.0.0"
indoc = "2.0.5"

[dev-dependencies]
rstest ="0.22.0"
